
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres
    environment:
      POSTGRES_DB: backend
      # You should definitely change the password in production
      POSTGRES_PASSWORD: root
      POSTGRES_USER: fred
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "backend", "-U", "fred"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
